# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'
steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'


- task: StyleCop
  inputs: 
     # Required arguments
     treatStyleCopViolationsErrorsAsWarnings: False
     sourcefolder: $(build.SourcesDirectory)
     maximumViolationCount: 1000
     allowableViolationCount: 0
     showOutput: False
     cacheResults: False
     forceFullAnalysis: True
     loggingfolder: $(build.StagingDirectory)
     summaryFileName: stylecopsummary.md
     detailedSummary: False

- script: dotnet test CarBackEnd/Car.Tests/Car.Tests.csproj  --logger trx
- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testRunner: VSTest
    testResultsFiles: '**/*.trx'


    
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/CarBackEnd/*.csproj'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'myWebsiteName'